account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
  path("", home, name="home"),
  path("stage/", stage, name="stage"),
  path("login/", login_view, name="login"),
  path("logout/", logout_user, name="logout"),
  path('register/', register, name='register'),
  path('subscription/', subscription, name='subscription'),
  path('verify/<str:token>', verify, name='verify'),
  path('subscribe/<str:price_id>', subscribe, name='subscribe'),
  path('stripe-webhook', stripe_webhook, name='stripe_webhook'),
  path('manage-subscription', manage_subscription, name='manage_subscription'),
  path('billing-portal', billing_portal, name='billing_portal'),
  path('add-credits/<str:kind>', add_credits, name='add_credits'),
  path('add-credits-success', add_credits_success, name='add_credits_success'),
  path('add-credits-cancel', add_credits_cancel, name='add_credits_cancel'),
  path(
    'upgrade-subscription/<str:price_id>',
    upgrade_subscription,
    name='upgrade_subscription'
  ),
  path(
    'downgrade-subscription',
    downgrade_subscription,
    name='downgrade_subscription'
  ),
  path('cancel-subscription', cancel_subscription, name='cancel_subscription'),
  path(
    'terms-and-conditions', terms_and_conditions, name='terms_and_conditions'
  ),
  path('privacy-policy', privacy_policy, name='privacy_policy'),
  path('refund-policy', refund_policy, name='refund_policy'),
  path('affiliate-program', affiliate_program, name='affiliate_program'),
]

hooks/urls.py
from django.urls import path
from . import views

app_name = 'hooks'

urlpatterns = [
  path('upload/', views.upload_hook, name='upload'),
  path(
    'processing/<str:task_id>/<str:aspect_ratio>/',
    views.processing,
    name='processing'
  ),
  path(
    'check_status/<str:task_id>/', views.check_task_status, name='check_status'
  ),
  path('download_zip/<str:task_id>/', views.download_zip, name='download_zip'),
  path(
    'download_output/<path:videopath>/',
    views.download_video,
    name='download_output'
  ),
  path(
    'processing_successful/<str:task_id>/',
    views.processing_successful,
    name='processing_successful'
  ),
  path(
    'validate-google-sheet-link/',
    views.validate_google_sheet_link,
    name='validate_google_sheet_link'
  ),
  path('validate-api-key/', views.validate_api_key, name='validate_api_key'),
]

hooks_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
  path("", include("account.urls", namespace="account")),
  path("admin/", admin.site.urls),
  path("hooks/", include("hooks.urls", namespace="hooks")),
  path("merge/", include("merger.urls", namespace="merger")),
  path(
    "password-reset/",
    auth_views.PasswordResetView.as_view(
      template_name="registration/reset_password.html",
      email_template_name="password_reset_email_template.html",
    ),
    name="password_reset",
  ),
  path(
    "password-reset/done/",
    auth_views.PasswordResetDoneView.as_view(
      template_name="password_reset_done.html"
    ),
    name="password_reset_done",
  ),
  path(
    "reset/<uidb64>/<token>/",
    auth_views.PasswordResetConfirmView.as_view(
      template_name="password_reset_confirm.html"
    ),
    name="password_reset_confirm",
  ),
  path(
    "reset/done/",
    auth_views.PasswordResetCompleteView.as_view(
      template_name="password_reset_complete.html"
    ),
    name="password_reset_complete",
  ),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
  def create_user(self, email, password=None, **extra_fields):
    if not email:
      raise ValueError('The Email field must be set')
    email = self.normalize_email(email)
    user = self.model(email=email, **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self, email, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)
    return self.create_user(email, password, **extra_fields)

class Plan(models.Model):
  stripe_price_id = models.CharField(max_length=255, null=True)
  name = models.CharField(max_length=50)
  price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
  price_per_hook = models.DecimalField(
    max_digits=5, decimal_places=2, null=True
  )
  hook_limit = models.IntegerField(default=0)

class StripeCustomer(models.Model):
  user = models.ForeignKey('User', on_delete=models.CASCADE, null=True)
  stripe_customer_id = models.CharField(max_length=255)

class Subscription(models.Model):
  plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
  stripe_subscription_id = models.CharField(max_length=255, null=True)
  customer = models.ForeignKey(
    StripeCustomer, on_delete=models.CASCADE, null=True
  )
  hooks = models.IntegerField(default=0)
  merge_credits = models.IntegerField(blank=True, null=True)
  current_period_end = models.IntegerField(default=0)

class User(AbstractUser):
  email = models.EmailField(unique=True, null=False, blank=False)
  api_key = models.CharField(max_length=255, blank=True, null=True)
  verification_token = models.CharField(max_length=100, blank=True, null=True)
  subscription = models.ForeignKey(
    Subscription, on_delete=models.SET_NULL, null=True
  )

  USERNAME_FIELD = "email"
  REQUIRED_FIELDS = []

  objects = CustomUserManager()

  def save(self, *args, **kwargs):
    self.username = self.email
    super().save(*args, **kwargs)

  def can_generate_video(self):
    return self.subscription.hooks >= 1

account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
  username = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'id': 'email',
        'type': 'email',
        'placeholder': 'Email'
      }
    )
  )
  password = forms.CharField(
    widget=forms.PasswordInput(
      attrs={
        'id': 'password',
        'type': 'password',
        'placeholder': 'Password'
      }
    )
  )

from django.core.mail import send_mail
from django.conf import settings

class ContactUsForm(forms.Form):
  full_name = forms.CharField(
    max_length=100,
    widget=forms.TextInput(
      attrs={
        "id": "full_name",
        "placeholder": "Enter Your Full Name",
        "type": "text",
      }
    ),
  )

  email = forms.EmailField(
    widget=forms.TextInput(
      attrs={
        "id": "email",
        "placeholder": "Enter your Email address",
        "type": "email",
      }
    )
  )
  message = forms.CharField(
    widget=forms.Textarea(
      attrs={
        "id": "message",
        'placeholder': "Write Us Your Question Here..."
      }
    )
  )

  def send(self):
    message = f"Full Name: {self.cleaned_data['full_name']}\n"
    message += f"Email: {self.cleaned_data['email']}\n"
    message += f"Message: {self.cleaned_data['message']}\n"

    send_mail(
      "Contact Us Form Submission",
      message,
      from_email=settings.EMAIL_HOST_USER,
      recipient_list=[settings.EMAIL_HOST_USER],
      fail_silently=False,
    )

account/views.py
from account.forms import ContactUsForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.contrib.auth import login, get_user_model, logout, authenticate
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.html import strip_tags
from .models import Subscription, StripeCustomer, Plan
import stripe
import uuid
from datetime import datetime

def stage(request):
  return render(request, 'stage.html')

def login_view(request):
  if request.user.is_authenticated:
    return redirect('hooks:upload')

  if request.method == 'POST':
    email = request.POST['email']
    password = request.POST['password']

    user = authenticate(request, username=email, password=password)

    if user is not None:
      if user.verification_token is None:
        _login(request, user)

        try:
          return redirect(request.session.get('next'))
        except:
          return redirect('hooks:upload')
      else:
        messages.error(
          request,
          'Your Email Address Is Not Verified. Please Verify Your Email Before Logging In.'
        )
    else:
      messages.error(request, 'Invalid Username or Password. Please Try Again.')

  next = request.GET.get('next', '')
  request.session['next'] = next
  return render(
    request,
    'registration/login.html',
  )

def logout_user(request):
  if request.user.is_authenticated:
    logout(request)

  return redirect('account:home')

def home(request):
  if request.user.is_authenticated:
    return redirect('hooks:upload')

  contact_us_form = ContactUsForm(request.POST or None)

  if request.method == 'POST':
    if contact_us_form.is_valid():
      try:
        contact_us_form.send()
      except Exception as e:
        print(f'An error occurred while sending contact us message {e}')
        messages.error(request, 'Failed To Send Message')
        return redirect(reverse('account:home') + '#Contact')

      messages.success(request, 'Message Sent Successfully')
      return redirect(reverse('account:home') + '#Contact')

  return render(
    request,
    'home.html',
    {
      'contact_us_form': contact_us_form,
      'plans': Plan.objects.all(),
    },
  )

def terms_and_conditions(request):
  return render(request, 'terms_and_conditions.html')

def privacy_policy(request):
  return render(request, 'privacy_policy.html')

def refund_policy(request):
  return render(request, 'refund_policy.html')

def affiliate_program(request):
  return render(request, 'affiliate_program.html')

def register(request):
  if request.method == 'POST':
    stripe.api_key = settings.STRIPE_SEC_KEY

    checkout_session_id = request.POST.get('session_id')

    name = request.POST.get('name')
    email = request.POST.get('email')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')

    if len(password1) < 6:
      messages.error(request, 'At Least 6 Characters Are Required')
      return render(
        request,
        'registration/register.html',
        context={'session_id': checkout_session_id}
      )

    if password1 != password2:
      messages.error(request, 'Passwords Do Not Match.')
      return render(
        request,
        'registration/register.html',
        context={'session_id': checkout_session_id}
      )

    User = get_user_model()
    if User.objects.filter(email=email).exists():
      messages.error(request, 'This Email Is Already Registered.')
      return render(
        request,
        'registration/register.html',
        context={'session_id': checkout_session_id}
      )

    user = User.objects.create_user(email=email, password=password1)
    user.first_name = name
    user.save()

    if checkout_session_id is None:
      free_plan = Plan.objects.get(id=3)
      customer = stripe.Customer.create(
        email=user.email,
        name=user.first_name,
      )
      stripe_customer = StripeCustomer(
        user=user, stripe_customer_id=customer.id
      )
      stripe_customer.save()
      subscription = Subscription(
        plan=free_plan,
        hooks=free_plan.hook_limit,
        merge_credits=free_plan.hook_limit * 5,
        customer=stripe_customer,
        stripe_subscription_id=None
      )
      subscription.save()
      user.subscription = subscription

      verification_token = str(uuid.uuid4())
      user.verification_token = verification_token

      user.save()

      send_html_email2(
        subject='Welcome to HooksMaster.io – Verify Your Email To Continue',
        message=None,
        from_email=settings.EMAIL_HOST_USER,
        to_email=user.email,
        html_file='verification.html',
        context={
          'first_name':
            user.first_name,
          'verification_url':
            settings.DOMAIN
            + reverse('account:verify', kwargs={'token': verification_token}),
        },
      )

      return render(
        request,
        'registration/register.html',
        context={
          'price_id': 'free',
          'success': True
        }
      )
    else:
      checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
      stripe_customer_id = checkout_session.customer

      customer_id = 0
      try:
        customer = StripeCustomer.objects.get(
          stripe_customer_id=stripe_customer_id
        )

        if customer is not None:
          customer.user = user
          customer.save()

          customer_id = customer.id
      except StripeCustomer.DoesNotExist:
        new_customer = StripeCustomer(
          user=user, stripe_customer_id=stripe_customer_id
        )
        new_customer.save()

        customer_id = new_customer.id

      try:
        subscription = Subscription.objects.get(customer_id=customer_id)

        if subscription is not None:
          user.subscription = subscription
          user.save()
      except Exception as _:
        messages.error(request, "Subscription Failed. Please Try Again Later.")
        return render(
          request,
          'registration/register.html',
          context={'session_id': checkout_session_id}
        )

      send_confirmation_email(email, user.first_name)

      _login(request, user)

      return redirect("hooks:upload")
  elif request.method == 'GET':
    checkout_session_id = request.GET.get('session_id')

    return render(
      request,
      'registration/register.html',
      context={'session_id': checkout_session_id}
    )

@csrf_exempt
def stripe_webhook(request):
  stripe.api_key = settings.STRIPE_SEC_KEY

  endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
  payload = request.body
  sig_header = request.META['HTTP_STRIPE_SIGNATURE']

  event = None
  try:
    event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
  except ValueError as _:
    return HttpResponse(status=400)
  except stripe.error.SignatureVerificationError as _:
    return HttpResponse(status=400)

  event_type = event['type']
  event_object = event['data']['object']

  if event_type == 'invoice.payment_succeeded':
    if event_object.billing_reason == 'subscription_create':
      try:
        customer_id = event_object.customer

        customer = None
        try:
          customer = StripeCustomer.objects.get(stripe_customer_id=customer_id)
        except StripeCustomer.DoesNotExist:
          customer = StripeCustomer(user=None, stripe_customer_id=customer_id)
          customer.save()

        prev_sub = None
        prev_sub_hooks = 0
        prev_sub_merges = 0
        try:
          prev_sub = Subscription.objects.get(customer_id=customer.id)

          if prev_sub is not None:
            if prev_sub.stripe_subscription_id is not None:
              stripe.Subscription.delete(prev_sub.stripe_subscription_id)

            prev_sub_hooks = prev_sub.hooks
            prev_sub_merges = prev_sub.merge_credits
        except Subscription.DoesNotExist:
          pass

        subscription_id = event_object.subscription
        price_id = event_object.lines.data[0].price.id
        plan = Plan.objects.get(stripe_price_id=price_id)
        subscription = Subscription(
          plan=plan,
          stripe_subscription_id=subscription_id,
          customer=customer,
          hooks=plan.hook_limit + prev_sub_hooks,
          merge_credits=(plan.hook_limit * 5) + prev_sub_merges
        )
        subscription.save()

        if customer.user is not None:
          customer.user.subscription = subscription
          customer.user.save()

          if prev_sub is not None:
            prev_sub.delete()
      except Exception as e:
        print(
          datetime.now().strftime("%H:%M:%S")
          + f': Error in stripe webhook: {e}'
        )
    elif event_object.billing_reason == 'subscription_cycle':
      try:
        price_id = event_object.lines.data[0].price.id
        plan = Plan.objects.get(stripe_price_id=price_id)

        subscription_id = event_object.subscription
        subscription = Subscription.objects.get(
          stripe_subscription_id=subscription_id
        )
        subscription.hooks = plan.hook_limit + subscription.hooks
        subscription.merge_credits = (
          plan.hook_limit * 5
        ) + subscription.merge_credits
        subscription.save()
      except Exception as e:
        print(
          datetime.now().strftime("%H:%M:%S")
          + f': Error in stripe webhook: {e}'
        )
  elif event_type == 'invoice.payment_failed':
    if event_object.billing_reason == 'subscription_create':
      messages.error(
        request,
        'Checkout error. Couldn\'t Complete Subsrciption Successfully. Please try again later.'
      )

      print(

account/templates/affiliate_program.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta http-equiv="Cache-Control"
          content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <link rel="stylesheet" href="{% static 'style.css' %}" />

    <link rel="icon"
          type="image/svg+xml"
          href="{% static 'assets/favicon.svg' %}" />
    <title>HooksMaster | Affiliate Program Policy</title>

    <script>
      function adjustZoom() {
        const screenWidth = window.innerWidth;
        if (screenWidth >= 1400 && screenWidth <= 1599) {
          document.body.style.zoom = '88%';
        }
        document.body.classList.remove('body-hidden');
      }
      document.addEventListener('DOMContentLoaded', adjustZoom);
      document.addEventListener('resize', adjustZoom);
      window.onload = function() {
        adjustZoom();
      };
    </script>

    <style>
      .content {
        max-width: 1500px;
        padding: 0 30px;
        margin: 50px auto;
        font-family: 'Plus Jakarta Sans', sans-serif;
      }

      .content h1 {
        margin-bottom: 20px;
      }

      .content h3 {
        margin-bottom: 10px;
      }

      .content p {
        margin-bottom: 20px;
      }

      .content p:last-of-type {
        margin-bottom: 0;
      }

      .content .before-list-items {
        margin-bottom: 0 !important;
      }

      .content ul {
        margin: 10px 35px;
      }
    </style>
  </head>
  <body class="body-hidden">
    <div class="root">
      <header>
        <a href="/">
          <img class="logo" src="{% static 'assets/logo.svg' %}" alt="logo" />
        </a>
        <div>
          <ul class="navigation">
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/#Portfolio">Portfolio</a>
            </li>
            <li>
              <a href="/#Pricing">Pricing</a>
            </li>
            <li>
              <a href="/#About">About</a>
            </li>
            <li>
              <a href="/#Contact">Contact</a>
            </li>
          </ul>

          <div class="line"></div>
          <div class="auth">
            <button class="login">
              <a class="links black" href="{% url 'account:login' %}">Login</a>
            </button>
            <button class="get_started">
              <span><a class="links white" href="#Pricing">Get started</a></span>
            </button>
          </div>
        </div>
        <div class="menu">
          <img src="{% static 'assets/menu.svg' %}" alt="menu" />
        </div>
      </header>
      <div class="menu_wrapper">
        <img class="close_menu"
             src="{% static 'assets/close.svg' %}"
             alt="close menu" />
        <ul class="navigation">
          <li>
            <a href="/" class="menu-a">Home</a>
          </li>
          <li>
            <a href="/#Portfolio" class="menu-a">Portfolio</a>
          </li>
          <li>
            <a href="/#Pricing" class="menu-a">Pricing</a>
          </li>
          <li>
            <a href="/#About" class="menu-a">About</a>
          </li>
          <li>
            <a href="/#Contact" class="menu-a">Contact</a>
          </li>
        </ul>
      </div>

      <div class="content">
        <h1>Affiliate Program Policy</h1>

        <h3>1. Introduction</h3>
        <p>
          The HooksMaster.io Affiliate Program allows you to earn a 30%
          recurring commission on customer subscriptions generated through your
          unique referral link.
        </p>

        <h3>2. Eligibility and Enrollment</h3>
        <p>
          Affiliates must complete an application and agree to these terms.
          Membership in the affiliate program is at the discretion of
          HooksMaster.io and may be revoked for violations of these terms.
        </p>

        <h3>3. Commission Structure</h3>
        <ul>
          <li>
            <strong>Payout Rate</strong>: Affiliates earn a 30% commission on
            recurring customer payments.
          </li>
          <li>
            <strong>Payout Schedule</strong>: Commissions are paid monthly,
            provided a minimum payout threshold is reached.
          </li>
        </ul>
        <p></p>

        <h3>4. Affiliate Responsibilities</h3>
        <p>
          Affiliates agree to promote HooksMaster.io responsibly, following
          ethical guidelines, and avoiding misleading claims or unauthorized
          branding use.
        </p>

        <h3>5. Termination of Affiliate Status</h3>
        <p>
          Affiliates may be removed from the program for violating these terms
          or misusing affiliate marketing guidelines. Upon termination, no
          further commissions will be earned.
        </p>

        <h3>Contact Information</h3>
        <p>
          For further questions or information, please contact
          support@hooksmaster.io.
        </p>
      </div>

      <footer>
        <div class="information">
          <img src="{% static 'assets/white_logo.svg' %}" alt="logo" />
          <p class="desktop_p">
            Every Facebook advertiser knows the power of a great
            <br />
            video hook. Now, with HooksMaster.io, you can create
            <br />
            winning hooks in minutes, without the hassle or
            <br />
            expense of hiring video editors.
          </p>
          <p class="mobile_p">
            Every Facebook advertiser knows the power of a
            <br />
            great video hook. Now, with HooksMaster.io, you
            <br />
            can create winning hooks in minutes, without the
            <br />
            hassle or expense of hiring video editors.
          </p>
          <ul class="socials">
            <li>
              <img src="{% static 'assets/facebook.svg' %}" alt="facebook" />
            </li>
            <li>
              <img src="{% static 'assets/twitter.svg' %}" alt="twitter" />
            </li>
            <li>
              <img src="{% static 'assets/linkedin.svg' %}" alt="linkedin" />
            </li>
          </ul>
        </div>
        <div class="navigation_bar">
          <div class="box">
            <h5>Company</h5>
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/#Portfolio">Portfolio</a>
              </li>
              <li>
                <a href="/#Pricing">Pricing</a>
              </li>
              <li>
                <a href="/#About">About</a>
              </li>
            </ul>
          </div>
          <div class="box">
            <h5>Help</h5>
            <ul>
              <li>
                <a href="/#Contact">Contact us</a>
              </li>
              <li>
                <a href="{% url 'account:terms_and_conditions' %}">Terms & Conditions</a>
              </li>
              <li>
                <a href="{% url 'account:privacy_policy' %}">Privacy policy</a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="module" src="{% static 'main.js' %}"></script>
  </body>
</html>

account/templates/password_reset_email_template.html
{% autoescape off %}
Hi {{ user.first_name }},

We received a request to reset your password. Click the link below to set a new password:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

This link will expire in 24 hours. If you didn’t request a reset, you can ignore this message.

Questions? Contact us at support@hooksmaster.io.

Best,
The HooksMaster.io Team

{% endautoescape %}

account/templates/verification.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body {
        font-family: 'Montserrat', sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
      }
      .container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
      }
      .header {
        text-align: center;
        margin-bottom: 20px;
      }
      .header img {
        max-width: 150px;
        cursor: pointer; /* Add a pointer for the clickable logo */
      }
      .content {
        margin: 20px 0;
      }
      .content h2 {
        color: #333;
      }
      .content p {
        color: #555;
      }
      .button {
        padding: 13px 25px;
        cursor: pointer;
        font-size: 16px;
        transition: all ease-out 0.2s;
        display: block;
        color: #ffffff !important;
        background-color: rgba(72, 90, 255, 1);
        border: 1px solid rgba(25, 25, 25, 1);
        border-bottom: 4px solid rgba(25, 25, 25, 1);
        border-right: 4px solid rgba(25, 25, 25, 1);
        border-left: 2px solid rgba(25, 25, 25, 1);
        border-radius: 50px;
        width: max-content;
        margin: 10px auto;
      }

      .button:hover {
        background-color: rgb(20, 42, 241);
      }

      a {
        text-decoration: none;
        cursor: pointer;
      }
      .footer {
        margin-top: 30px;
        text-align: center;
        font-size: 0.9em;
        color: #555;
      }
      .bold {
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header"></div>
      <div class="content">
        <h2>Hi {{ first_name }},</h2>
        <p>
          Your <span style="font-weight: 600">HooksMaster.io</span> account is
          live! You now have the tools to create high-converting Video Sales
          Letters in minutes.
        </p>
        <p style="font-weight: 600">
          Visit the link below to verify your email and get started.
        </p>
        <a href="{{ verification_url }}" class="button">Verify Account</a>
        <p>Cheers,</p>
      </div>
      <div class="footer">
        <p class="bold">The HooksMaster.io Team</p>
      </div>
    </div>
  </body>
</html>