account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
  path("", home, name="home"),
  path("stage/", stage, name="stage"),
  path("login/", login_view, name="login"),
  path("logout/", logout_user, name="logout"),
  path('register/', register, name='register'),
  path('subscription/', subscription, name='subscription'),
  path('verify/<str:token>', verify, name='verify'),
  path('subscribe/<str:price_id>', subscribe, name='subscribe'),
  path('stripe-webhook', stripe_webhook, name='stripe_webhook'),
  path('manage-subscription', manage_subscription, name='manage_subscription'),
  path('billing-portal', billing_portal, name='billing_portal'),
  path('add-credits/<str:kind>', add_credits, name='add_credits'),
  path('add-credits-success', add_credits_success, name='add_credits_success'),
  path('add-credits-cancel', add_credits_cancel, name='add_credits_cancel'),
  path(
    'upgrade-subscription/<str:price_id>',
    upgrade_subscription,
    name='upgrade_subscription'
  ),
  path(
    'downgrade-subscription',
    downgrade_subscription,
    name='downgrade_subscription'
  ),
  path('cancel-subscription', cancel_subscription, name='cancel_subscription'),
  path(
    'terms-and-conditions', terms_and_conditions, name='terms_and_conditions'
  ),
  path('privacy-policy', privacy_policy, name='privacy_policy'),
  path('refund-policy', refund_policy, name='refund_policy'),
  path('affiliate-program', affiliate_program, name='affiliate_program'),
]

hooks/urls.py
from django.urls import path
from . import views

app_name = 'hooks'

urlpatterns = [
  path('upload/', views.upload_hook, name='upload'),
  path(
    'processing/<str:task_id>/<str:aspect_ratio>/',
    views.processing,
    name='processing'
  ),
  path(
    'check_status/<str:task_id>/', views.check_task_status, name='check_status'
  ),
  path('download_zip/<str:task_id>/', views.download_zip, name='download_zip'),
  path(
    'download_output/<path:videopath>/',
    views.download_video,
    name='download_output'
  ),
  path(
    'processing_successful/<str:task_id>/',
    views.processing_successful,
    name='processing_successful'
  ),
  path(
    'validate-google-sheet-link/',
    views.validate_google_sheet_link,
    name='validate_google_sheet_link'
  ),
  path('validate-api-key/', views.validate_api_key, name='validate_api_key'),
]

hooks_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
  path("", include("account.urls", namespace="account")),
  path("admin/", admin.site.urls),
  path("hooks/", include("hooks.urls", namespace="hooks")),
  path("merge/", include("merger.urls", namespace="merger")),
  path(
    "password-reset/",
    auth_views.PasswordResetView.as_view(
      template_name="registration/reset_password.html",
      email_template_name="password_reset_email_template.html",
    ),
    name="password_reset",
  ),
  path(
    "password-reset/done/",
    auth_views.PasswordResetDoneView.as_view(
      template_name="password_reset_done.html"
    ),
    name="password_reset_done",
  ),
  path(
    "reset/<uidb64>/<token>/",
    auth_views.PasswordResetConfirmView.as_view(
      template_name="password_reset_confirm.html"
    ),
    name="password_reset_confirm",
  ),
  path(
    "reset/done/",
    auth_views.PasswordResetCompleteView.as_view(
      template_name="password_reset_complete.html"
    ),
    name="password_reset_complete",
  ),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merger/urls.py
from django.urls import path
from . import views

app_name = 'merger'

urlpatterns = [
  path('', views.index, name='index'),
  path('upload/', views.upload_files, name='upload_files'),
  path('processing/<str:task_id>/', views.processing, name='processing'),
  path('get_progress/<str:task_id>', views.get_progress, name='get_progress'),
  path(
    'check_status/<str:task_id>/', views.check_task_status, name='check_status'
  ),
  path('download_zip/<str:task_id>/', views.download_zip, name='download_zip'),
  path(
    'download_output/<path:videopath>/',
    views.download_video,
    name='download_output'
  ),
  path(
    'processing_successful/<str:task_id>/',
    views.processing_successful,
    name='processing_successful'
  ),
]

hooks/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_video_file(value):
  # List of allowed video mime types
  valid_mime_types = [
    'video/mp4', 'video/x-m4v', 'video/quicktime', 'video/x-msvideo',
    'video/x-ms-wmv'
  ]
  file_mime_type = value.file.content_type

  if file_mime_type not in valid_mime_types:
    raise ValidationError(
      f'Unsupported file type: {file_mime_type}. Please upload a valid video file.'
    )

class Hook(models.Model):
  hooks_content = models.FileField(
    max_length=500,
    upload_to='hooks_videos/',
    blank=True,
    null=True,
    validators=[validate_video_file]
  )
  google_sheets_link = models.URLField(max_length=500, blank=True, null=True)
  eleven_labs_api_key = models.CharField(max_length=255, blank=True, null=True)
  voice_id = models.CharField(max_length=255, blank=True, null=True)
  box_color = models.CharField(max_length=7, default='#485AFF')
  font_color = models.CharField(max_length=7, default='#FFFFFF')
  task_id = models.CharField(max_length=1000, unique=True)
  parallel_processing = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)

  STATUS_CHOICES = [
    ('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'),
    ('option4', 'option4')
  ]
  dimension = models.CharField(
    max_length=30, choices=STATUS_CHOICES, default='option1'
  )

  def __str__(self):
    return str(self.id)

class Task(models.Model):
  task_id = models.CharField(max_length=255)
  status = models.CharField(max_length=20, default='processing')
  aspect_ratio = models.CharField(max_length=255, default='option1')
  video_links = models.JSONField(null=True, blank=True)

  def __str__(self) -> str:
    return self.status

class Package(models.Model):
  name = models.CharField(max_length=100)
  price = models.PositiveIntegerField()
  stripe_id = models.CharField(max_length=200)
  video_limit = models.PositiveIntegerField()
  price_per_video = models.FloatField(null=True, blank=True)

  def __str__(self) -> str:
    return self.name

hooks/forms.py
from django import forms
from .models import Hook

class HookForm(forms.ModelForm):
  class Meta:
    model = Hook
    fields = [
      'hooks_content', 'google_sheets_link', 'eleven_labs_api_key', 'voice_id',
      'box_color', 'font_color'
    ]

    widgets = {
      'hooks_content':
        forms.ClearableFileInput(
          attrs={
            'id': 'hooks',
            'accept': 'video/mp4,video/x-m4v,video/*',
          }
        ),
      'google_sheets_link':
        forms.URLInput(
          attrs={
            'id': 'google_link',
            'placeholder': 'Paste URL Link',
          }
        ),
      'eleven_labs_api_key':
        forms.TextInput(
          attrs={
            'id': 'api_key',
            'placeholder': 'Paste API Key',
          }
        ),
      'voice_id':
        forms.TextInput(
          attrs={
            'id': 'voice_id',
            'placeholder': 'Enter Voice ID',
          }
        ),
      'box_color':
        forms.TextInput(
          attrs={
            'type': 'color',
            'class': 'color-input',
            'value': '#485AFF',
            'id': 'boxcolor',
            'required': 'required',
          }
        ),
      'font_color':
        forms.TextInput(
          attrs={
            'type': 'color',
            'class': 'color-input',
            'value': '#FFFFFF',
            'id': 'fontcolor',
            'required': 'required',
          }
        ),
    }

hooks/views.py
import logging
import tempfile
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, FileResponse
from django.conf import settings

from .forms import HookForm

from .tools.utils import generate_task_id
from .tools.processor import process_files

from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from .models import Task
from account.models import Plan

import threading

import zipfile
import io

import requests
from .tools.spreadsheet_extractor import fetch_google_sheet_data

logging.basicConfig(level=logging.DEBUG)

def background_processing(task_id, user_sub, aspect_ratio):

  try:
    temp_dir = tempfile.mkdtemp(prefix=f"task_{task_id}_")
    logging.info(f'temp_dir ->, {temp_dir}')

    # Process the files and get video links and credits used
    video_links, credits_used = process_files(
      temp_dir,
      task_id,
      user_sub.plan.name.lower() == 'free'
      # FIXME: and user_sub.current_period_end is None
      ,
      aspect_ratio
    )
    logging.info(f"{video_links}: Video Links")
    logging.info(f'{credits_used} Credits Used.')

    # Reduce user credits and save profile
    user_sub.hooks -= credits_used
    user_sub.save()

    # Update the task status
    task = Task.objects.get(task_id=task_id)
    task.status = 'completed'
    task.video_links = video_links
    task.aspect_ratio = aspect_ratio
    task.save()

  except Exception as e:
    logging.error(f"Error during background processing: {e}")

@login_required
def upload_hook(request):
  if not request.user.is_authenticated:
    return redirect('account:home')

  hook = None
  if request.method == 'POST':
    task_id = generate_task_id()
    logging.info(f'Task ID generated --> {task_id}')

    Task.objects.create(task_id=task_id, status='processing')
    logging.info(f'A Task object created for task id --> {task_id}')

    parallel_processing = True

    form = HookForm(request.POST, request.FILES)
    is_valid_resolution = request.POST.get('resolution') in [
      'option1', 'option2', 'option3', 'option4'
    ]
    is_valid_form = form.is_valid() and \
                    is_valid_resolution
    if is_valid_form:
      hook = form.save(commit=False)
      hook.task_id = task_id
      hook.parallel_processing = parallel_processing
      hook.dimension = request.POST.get('resolution')
      hook.save()

      return redirect(
        'hooks:processing', task_id=task_id, aspect_ratio=hook.dimension
      )
    else:
      return render(request, 'upload_hook.html', {'form': form, 'hook': hook})
  else:
    form = HookForm()

  return render(request, 'upload_hook.html', {'form': form, 'hook': hook})

@login_required
def processing(request, task_id, aspect_ratio):

  # Check if the user has enough credits
  user_sub = request.user.subscription
  if user_sub.hooks <= 0:
    # You can change the url below to the stripe URL
    # return redirect('hooks:no_credits')  # Redirect to an error page or appropriate view
    return HttpResponse(
      "You don't have enough credits, buy and try again!", status=404
    )

  thread = threading.Thread(
    target=background_processing, args=(task_id, user_sub, aspect_ratio)
  )
  thread.start()

  return render(
    request, 'processing.html', {
      'task_id': task_id,
      'aspect_ratio': aspect_ratio,
    }
  )

@login_required
def check_task_status(request, task_id):
  task = get_object_or_404(Task, task_id=task_id)

  # Return task status and video links (if processing is completed)
  return JsonResponse(
    {
      'status': task.status,
      'video_links': task.video_links if task.status == 'completed' else None
    }
  )

def processing_successful(request, task_id):
  task = get_object_or_404(Task, task_id=task_id)

  return render(
    request, 'processing_successful.html', {
      'task_id': task_id,
      'video_links': task.video_links,
      'plans': Plan.objects.all(),
    }
  )

def download_video(request, videopath):
  if not os.path.exists(videopath):
    return HttpResponse("Video not found", status=404)

  response = FileResponse(open(videopath, 'rb'), content_type='video/mp4')
  response['Content-Disposition'
           ] = f'attachment; filename="{os.path.basename(videopath)}"'

  return response

def download_zip(request, task_id):
  task = get_object_or_404(Task, task_id=task_id)
  videos = task.video_links

  zip_buffer = io.BytesIO()

  with zipfile.ZipFile(zip_buffer, 'w') as zip_file:
    for idx, video in enumerate(videos):
      if os.path.exists(video['video_link']):
        file_name = os.path.basename(video['video_link'])

        # Add the file to the zip archive
        zip_file.write(video['video_link'], file_name)

  zip_buffer.seek(0)

  # Create a response with the zip file for downloading
  response = HttpResponse(zip_buffer, content_type='application/zip')
  response['Content-Disposition'] = f'attachment; filename="hook_videos.zip"'

  return response

@login_required
def validate_google_sheet_link(request):
  if request.method == 'POST':
    google_sheets_link = request.POST.get('google_sheets_link')

    try:
      # Attempt to fetch the Google Sheets data for validation
      fetch_google_sheet_data(google_sheets_link)
      return JsonResponse({'valid': True})
    except ValueError as ve:
      return JsonResponse({'valid': False, 'error': str(ve)})
    except Exception as e:
      return JsonResponse({'valid': False, 'error': str(e)})

  return JsonResponse({'valid': False, 'error': 'Invalid request method.'})

def validate_api_key(request):
  if request.method == 'POST':
    api_key = request.POST.get('eleven_labs_api_key', '')
    voice_id = request.POST.get(
      'voice_id'
    )  # Replace with a valid default voice ID to test the API key

    # Try making a request to Eleven Labs API to validate the key
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {"xi-api-key": api_key}
    data = {
      "text": "Test voice synthesis",  # Small test text to avoid large requests
      "model_id": "eleven_monolingual_v1",
      "voice_settings": {
        "stability": 0.5,
        "similarity_boost": 0.75
      }
    }

    try:
      response = requests.post(url, json=data, headers=headers)

      if response.status_code == 200:
        return JsonResponse({'valid': True})
      else:
        error_detail = response.json().get('detail', {})

        import json
        print(json.dumps(error_detail))

        return JsonResponse(
          {
            'valid': False,
            'error': error_detail['status'],
            'message': error_detail['message'],
          }
        )
    except requests.exceptions.RequestException as _:
      return JsonResponse(
        {
          'valid': False,
          'error': 'Error Connecting To Eleven Labs API',
          'message': 'Error Connecting To Eleven Labs API',
        }
      )

hooks/templates/processing_successful.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'processing_successful.css' %}" />

    <!-- Font Awesome Icons -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />

    <link rel="stylesheet" href="{% static 'profile.css' %}" />
    <link rel="stylesheet" href="{% static 'input.css' %}" />

    <link rel="icon"
          type="image/svg+xml"
          href="{% static 'assets/favicon.svg' %}" />
    <title>Hooks Generated Successfully</title>
    <style>
      body {
        font-family: 'Plus Jakarta Sans', sans-serif;
        margin: 0;
        padding: 0;
      }

      .credit-score {
        font-family: inherit;
      }

      [data-tooltip] {
        cursor: not-allowed;
        position: relative;
      }

      [data-tooltip]:after {
        content: attr(data-tooltip);
        padding: 6px 8px;
        position: absolute;
        left: 50%;
        bottom: 100%;
        transform: translateX(-50%);
        background-color: #000000aa;
        width: max-content;
        opacity: 0;
        visibility: hidden;
        transition: all 0.2s ease-out;
        color: #ffffff;
        border-radius: 6px;
      }

      [data-tooltip]:hover:after {
        opacity: 1;
        visibility: visible;
      }

      .root>.content {
        width: 100%;
        margin: 0 auto;
      }

      a.upgrade {
        padding: 12px 7px;
        text-transform: capitalize;
        font-weight: 600;
        width: 100%;
        display: block;
        text-align: center;
        border: 1px solid rgba(25, 25, 25, 1);
        border-bottom: 5px solid rgba(25, 25, 25, 1);
        border-right: 5px solid rgba(25, 25, 25, 1);
        border-left: 2px solid rgba(25, 25, 25, 1);
        border-radius: 50px;
        background-color: white;
        color: rgba(25, 25, 25, 1);
        transition: all ease-in 0.2s;
        text-decoration: none;
        color: #000000;
      }

      a.upgrade:hover {
        background-color: rgba(72, 90, 255, 1);
        color: white;
      }

      .card a {
        text-decoration: none;
      }

      .plans-popup-outer {
        padding: 46px;
        position: relative;
        background: white;
        border-radius: 16px
      }

      .plans-popup-container {
        display: flex;
        position: fixed;
        z-index: 1000;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        justify-content: center;
        align-items: center;
      }

      .hidden {
        display: none;
      }

      .close-popup {
        width: 25px;
        height: 25px;
        position: absolute;
        right: 10px;
        top: 10px;
        background-color: lightgray;
        border-radius: 50%;
        cursor: pointer;
      }

      .close-popup img {
        width: 15px;
        height: 15px;
        position: absolute;
        top: 5px;
        left: 5px;
      }

      .plans {
        display: grid;
        grid-template-columns: repeat(3, 324px);
        justify-content: center;
        gap: 18px;
        max-width: 1704px;
      }

      .box {
        background-color: #fff;
        padding: 28px 35px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1),
          0 6px 20px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        border-top: 1px solid rgba(0, 0, 0, 1);
        border-left: 1px solid rgba(0, 0, 0, 1);
        border-right: 4px solid rgba(0, 0, 0, 1);
        border-bottom: 5px solid rgba(0, 0, 0, 1);
        width: 328px;
        gap: 29px;
        font-family: 'Plus Jakarta Sans', sans-serif;
      }

      .box-head {
        color: rgba(72, 90, 255, 1);
        text-transform: capitalize;
        font-size: 16px;
        font-weight: 600;
        line-height: 28px;
        text-align: center;
        font-family: 'Plus Jakarta Sans', sans-serif;
      }

      .box-head2 {
        color: white;
      }

      .box p {
        text-transform: capitalize;
        width: 100%;

      }

      .box-head p {
        font-size: 16px;
        font-weight: 400;
      }

      .p-excl {
        color: rgba(255, 255, 255, 0.7);
        text-align: center;
        font-size: 13px;
        font-weight: 500;
        text-transform: lowercase;
        font-family: 'Plus Jakarta Sans', sans-serif;
      }

      #p {
        font-size: 16px;
        font-weight: 400;
        line-height: 42px;
      }

      .box p {
        margin-bottom: .6787rem;
      }

      .price {
        display: flex;
        align-items: last baseline;
        justify-content: center;
      }

      .price span {
        display: flex;
        align-items: self-end;
        font-size: 14px;
        font-weight: 400;
        margin-left: 10px;
        text-align: center;
        text-transform: lowercase;
      }

      .pb {
        color: rgba(0, 0, 0, 1);
      }

      .i-blue {
        color: rgba(72, 90, 255, 1);
      }

      .price h1 {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-size: 40px;
        font-weight: 700;
      }

      .pro h1 {
        color: white;
      }

      .p-cent {
        color: rgba(154, 154, 154);
        text-align: center;
        font-size: 13px;
        font-weight: 500;
        text-transform: lowercase;
        font-family: 'Plus Jakarta Sans', sans-serif;
      }

      i {
        color: rgba(72, 90, 255, 1);
        margin-right: 10px;
        font-size: 1.2rem;
      }

      .box button {
        border: 1px solid rgba(25, 25, 25, 1);
        border-bottom: 4px solid rgba(25, 25, 25, 1);
        border-right: 4px solid rgba(25, 25, 25, 1);
        border-left: 2px solid rgba(25, 25, 25, 1);
        border-radius: 50px;
        width: 100%;
        color: rgba(25, 25, 25, 1);
        background-color: #fff;
        padding: 12px 7px;
        text-transform: capitalize;
        font-weight: 600;
        cursor: pointer;
        transition: all ease-in 0.3s;
        font-size: 16px;
      }

      .fa-check2 {
        color: white;
      }

      .fa-check {
        font-size: 15px;
      }

      .excl {
        background-color: rgba(72, 90, 255, 1);
        color: white;
      }

      #up {
        border: 1px solid rgba(25, 25, 25, 1);
        border-bottom: 5px solid rgba(25, 25, 25, 1);
        border-right: 5px solid rgba(25, 25, 25, 1);
        border-left: 2px solid rgba(25, 25, 25, 1);
        border-radius: 50px;
        background-color: white;
        color: rgba(25, 25, 25, 1);
        transition: all ease-in 0.2s;
      }

      #up:hover {
        background-color: rgba(72, 90, 255, 1);
        color: white;
      }

      .box button:hover {
        background-color: rgba(72, 90, 255, 1);
        color: white;
      }
    </style>
  </head>
  <body>
    <div class="root">
      <header class="admin-header">
        <div class="container">
          <div class="header-two">
            <div class="hm-logo text-center">
              <img src="{% static 'assets/white_logo.svg' %}"
                   alt="VSL Logo"
                   onclick="window.location.href='{% url 'account:home' %}'"
                   style="cursor: pointer" />
            </div>
            <div class="header-profile">
              <div class="credit-score">
                <span>Credits Remaining:</span> <span>{{ request.user.subscription.hooks }}</span>
              </div>
              <a href="#!" class="profile-icn">
                <img src="{% static 'assets/user.svg' %}" alt="User Profile" />
              </a>
            </div>
            <div class="profile-dialog">
              <div class="user">
                <h4>{{ request.user.first_name }}</h4>
                <p>{{ request.user.email }}</p>
              </div>
              <div class="buttons">
                <button onclick="window.location.href='{% url "account:manage_subscription" %}'">
                  Manage Subscription
                </button>
                {% if request.user.subscription.plan.name|lower == 'free' %}
                  <button data-tooltip="Only Available On Paid Plans"
                          style="cursor: not-allowed;
                                 color: #999999">Go To Video Merger</button>
                {% else %}
                  <button onclick="window.location.href='{% url "merger:index" %}'">
                    Go To Video Merger
                  </button>
                {% endif %}
                <button>
                  Credit left <span>{{ request.user.subscription.hooks }}</span>
                </button>
                <button>Affiliate</button>
                <button onclick="window.location.href='{% url "account:logout" %}'">
                  Logout
                </button>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div class="content">
        <div class="success_block">
          <div class="head">
            <a href="{% url 'hooks:upload' %}"
               style="display: flex;
                      align-items: center;
                      margin-right: 32px">
              <img src="{% static 'assets/arrow_left.svg' %}" alt="arrow" />
            </a>
            <h5>Success</h5>
          </div>
          {% if video_links %}
            <ul class="info_block">
              {% for video in video_links %}
                <li>
                  <a href="{% url "hooks:download_output" videopath=video.video_link %}"
                     style="text-decoration: underline;
                            color: #485aff"
                     onclick="downloadFile(event)">{{ video.file_name }}</a>
                </li>
              {% endfor %}
            </ul>
            <button onclick="downloadAllAsZip()">Download All as Zip</button>

            {% if request.user.subscription.plan.name|lower == 'free' %}
              <a data-tooltip="Only Available On Paid Plans"
                 style="cursor: not-allowed;
                        color: #999999">Go To Video Merger</a>
            {% else %}
              <a href="{% url 'merger:index' %}" id="merger">Go To Video Merger</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>

    <div class="plans-popup-container hidden">
      <div class="plans-popup-outer">
        <div class="close-popup">
          <img src="{% static 'assets/close.svg' %}" alt="" />
        </div>

        <div class="plans" style="grid-template-columns: repeat(2, 324px)">
          <!-- Growth Plan -->
          <div class="box">
            <p class="box-head">{{ plans.0.name }}</p>
            <div class="price">
              <h1 class="pro">${{ plans.0.price|floatformat:0 }}</h1>
              <span>/Month</span>
            </div>
            <p class="p-cent">${{ plans.0.price_per_hook }} /hook</p>
            <p id="p" class="pb">
              <i class="fa-solid fa-check"></i> {{ plans.0.hook_limit }} Hooks per month
            </p>
            <a class="upgrade"
               href="{% url 'account:upgrade_subscription' price_id=plans.0.stripe_price_id %}?success_path=/hooks/upload&cancel_path=/hooks/upload">Upgrade Subscription</a>
          </div>

          <!-- Pro Plan -->
          <div class="box excl">
            <p class="box-head box-head2">{{ plans.1.name }}</p>
            <div class="price">
              <h1>${{ plans.1.price|floatformat:0 }}</h1>
              <span>/Month</span>
            </div>
            <p class="p-excl ">${{ plans.1.price_per_hook }} /hook</p>
            <p id="p">
              <i class="fa-solid fa-check fa-check2"></i>{{ plans.1.hook_limit }} Hooks per month
            </p>
            <a class="upgrade"
               href="{% url 'account:upgrade_subscription' price_id=plans.1.stripe_price_id %}?success_path=/hooks/upload&cancel_path=/hooks/upload">Upgrade Subscription</a>
          </div>
        </div>
      </div>
    </div>

    <script>
      function downloadAllAsZip() {
        if ('{{ request.user.subscription.plan.name|lower }}' === 'free') {
          document.querySelector('.plans-popup-container').classList.remove('hidden');
        }

        window.location.href = "{% url 'hooks:download_zip' task_id=task_id %}"
      }

      function downloadFile(event) {
        if ('{{ request.user.subscription.plan.name|lower }}' === 'free') {
          document.querySelector('.plans-popup-container').classList.remove('hidden');
        }
      }

      document.querySelector('.close-popup').addEventListener('click', () => {
        document.querySelector('.plans-popup-container').classList.add('hidden');
      });

      const user = document.querySelector(".user");
      const menu = document.querySelector(".menu");

      user.addEventListener("click", function() {
        if (menu.style.display === "block") {
          menu.style.display = "none"
        } else {
          menu.style.display = "block"
        }
      });

      const profilePic = document.querySelector(".profile-icn");
      const profileDialog = document.querySelector(".profile-dialog");
      profilePic.addEventListener("click", () => {
        profileDialog.classList.toggle("show");
      });
    </script>
  </body>
</html>